### PR TITLE
use non-relative import instead

### PR DESCRIPTION
**Pull request by 3raphat**
# Description

use non-relative import instead

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Refactor or other

# Checklist:

- [ ] I have run `pnpm format` and my code don't have any linting issues
  
  
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Leomotors — COMMENTED** [review]
Have you tried running the bot locally? I don't think it will work if we don't transform the path during compilation. (TypeScript doesn't do that for us)

**Comment by 3raphat** [comment]
It works for me

**Comment by Gusb3ll** [comment]
@3raphat Please fix conflict kub 🙏 , also is this run with `pnpm start` after building and not only dev? Please provided screenshot also kub

**Comment by Gusb3ll** [comment]
Smoke test passed, I think we could safely merged this now 

cc @Leomotors @dtinth

**Review by Gusb3ll — APPROVED** [review]

**Comment by dtinth** [comment]
I think the smoke test pass because the file that actually uses `@/` import is not used in the smoke test, so I am still not confident…

I have updated the smoke test to handle this case (#71). Let’s see…

**Review by dtinth — CHANGES_REQUESTED** [review]
when running the smoke test, it appears that some modules cannot be loaded.

image

@3raphat when testing the bot, please don't use `pnpm dev` krub — do this instead:

```sh
pnpm build
pnpm start
```

this matches the behavior in production.

**Comment by 3raphat** [comment]
Ohh sorry krub🙏 I forgot about it.

**Comment by Leomotors** [comment]
fyi, this PR is similar to #17

**Pull request closed without merging**
