### PR TITLE
ci: update ci job name

### PR DESCRIPTION
**Pull request by Leomotors**
# Description

Update CI Job name so that it make more senses.
Added few more spaces so it does not look dense.

## Type of change

- [X] Refactor or other

# Checklist:

- [X] I have run `pnpm format` and my code don't have any linting issues

### CODE REVIEW

**Comment by Leomotors** [comment]
Reminder: Add this CI back to branch protection rules (Need to remove because name changed)

**Review by dtinth — APPROVED** [review]
please update branch protection rules afterwards, otherwise merging will be blocked

**Review by dtinth — APPROVED** [review]
please update branch protection rules afterwards, otherwise merging will be blocked

**Review by Gusb3ll — APPROVED** [review]

**Comment by Gusb3ll** [comment]
@Leomotors Please fix CI krubb

**Pull request merged**
